# Generated by Django 5.1.15 on 2026-09-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("father", models.CharField(blank=True, max_length=255, null=True)),
                ("mother", models.CharField(blank=True, max_length=255, null=True)),
                ("gfather", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Jockey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kaggle_rid",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("distance", models.CharField(blank=True, max_length=50, null=True)),
                ("condition", models.CharField(blank=True, max_length=100, null=True)),
                ("race_class", models.CharField(blank=True, max_length=50, null=True)),
                ("winning_time", models.FloatField(blank=True, null=True)),
                ("prize", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="racing.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaceEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.FloatField(blank=True, null=True)),
                ("saddle", models.FloatField(blank=True, null=True)),
                ("weight_carried", models.FloatField(blank=True, null=True)),
                ("decimal_price", models.FloatField(blank=True, null=True)),
                ("is_fav", models.BooleanField(default=False)),
                ("head_gear", models.CharField(blank=True, max_length=50, null=True)),
                ("rpr", models.FloatField(blank=True, null=True)),
                ("tr", models.FloatField(blank=True, null=True)),
                ("or_rating", models.FloatField(blank=True, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("margin", models.FloatField(blank=True, null=True)),
                ("res_win", models.BooleanField(blank=True, null=True)),
                (
                    "horse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="racing.horse",
                    ),
                ),
                (
                    "jockey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="racing.jockey",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="racing.race",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="racing.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Race Entries",
                "unique_together": {("race", "horse")},
            },
        ),
    ]
