# Generated by Django 5.1.15 on 2026-09-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racing", "0002_alter_course_id_alter_horse_id_alter_jockey_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="raceentry",
            name="age",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="raceentry",
            name="res_win",
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
