# Generated by Django 5.1.15 on 2026-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("racing", "0003_alter_race_date_alter_raceentry_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceentry",
            name="decimal_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="raceentry",
            index=models.Index(
                fields=["race", "res_win"], name="racing_race_race_id_579ca7_idx"
            ),
        ),
    ]
